services:
  - type: web
    name: findyourflatmates
    env: static
    buildCommand: npm install && npm run build:web
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
